name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v4.0.3
      with:
        major_pattern: "major:"
        minor_pattern: "feat:"
        format: "${major}.${minor}.${patch}-prerelease${increment}"
        id: version  
    #- name: Docker login
    #  env:
    #    DOCKER_USER: ${{secrets.DOCKER_USER}}
    #    DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
    #  run:
    - name: Docker login
      env: 
        NEW_VERSION: ${{steps.version.outputs.version}}
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin
        echo "New version: $NEW_VERSION!!!!!!"
      
    # - name: Build Docker Image
    #   run: |
    #     docker build -t cesaralla/docker-graphql:0.0.2 .
    #     docker build -t cesaralla/docker-graphql:latest .
    # - name: Push Docker Image
    #   run: |
    #     docker push cesaralla/docker-graphql:0.0.2
    #     docker push cesaralla/docker-graphql:latest
    
        
    
        
        
      
    
   # - name: Build the Docker image
   #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
