name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    #- name: Docker login
    #  env:
    #    DOCKER_USER: ${{secrets.DOCKER_USER}}
    #    DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
    #  run:
    - name: Docker login
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin
    - name: Build Docker Image
      run: |
        docker build -t cesaralla/docker-graphql:0.0.2 .
        docker build -t cesaralla/docker-graphql:latest .
    - name: Push Docker Image
      run: |
        docker push cesaralla/docker-graphql:0.0.2
        docker push cesaralla/docker-graphql:latest
        
    
        
        
      
    
   # - name: Build the Docker image
   #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
